os:
- linux
sudo: false
language:
- python
python:
- 2.7
addons:
  apt:
    packages:
    - cmake
    - libssl-dev
    - libsasl2-dev
    - sasl2-bin
    - swig
    - python-dev
    - valgrind
    - ruby
    - ruby-dev
    - python3-dev
    - php5
install:
- pip install --upgrade pip
- pip install tox
- gem install rspec
- gem install simplecov || true
- gem install minitest
before_script:
- export PATH=${HOME}/.local/bin:${PATH}
- mkdir Build
- cd Build
- cmake .. -DCMAKE_INSTALL_PREFIX=$PWD/install -DTOX_ENVLIST="py26,py27,py35"
script:
- cmake --build . --target install && ctest -V
